import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Navigation from '@/components/Navigation';
import { Frame } from '@/components/Frame';
import { Footer } from '@/components/Footer';
import { Padding } from '@/components/Padding';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Frame>
            <Padding>
              <Navigation />
              {children}
            </Padding>
            <Footer></Footer>
          </Frame>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
